name: binus_marketplace
description: BINUS Student Marketplace - Jual beli barang & jasa khusus mahasiswa BINUS

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

# Konfigurasi icon launcher
# Jalankan: dart run flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#1565C0"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Font (otomatis download, tidak perlu file .ttf manual)
  google_fonts: ^6.2.1

  # HTTP & API
  http: ^1.2.0
  http_parser: ^4.0.2
  dio: ^5.4.3

  # State Management
  provider: ^6.1.2

  # Real-time Chat
  socket_io_client: ^2.0.3+1

  # Local Storage (token, preferences)
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.0.0

  # Image
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  cross_file: ^0.3.4

  # UI
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0
  fluttertoast: ^8.2.5
  badges: ^3.1.2

  # Utils
  intl: ^0.20.2
  timeago: ^3.6.1

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
