# nixpacks.toml
# Taruh di root folder Backend/
# File ini override perilaku default Nixpacks

[phases.install]
# Ganti default 'npm ci' → 'npm install'
# npm ci butuh package-lock.json yang sempurna
# npm install lebih fleksibel dan cocok untuk development
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build", "npx prisma generate"]

[start]
cmd = "npx prisma migrate deploy && node dist/src/main"

[healthcheck]
enabled = false
