# railway.toml
# Taruh di root folder Backend/

[build]
builder = "NIXPACKS"
# Ganti npm ci → npm install supaya tidak cek package-lock.json
buildCommand = "npm install && npm run build && npx prisma generate"

[deploy]
startCommand = "npx prisma migrate deploy && node dist/src/main"
healthcheckPath = "/api"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
